# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FaceSample.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x46\x61\x63\x65Sample.proto\"\xdd\x01\n\nFaceSample\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x12\x12\n\nhasTracked\x18\x03 \x01(\x08\x12\x19\n\x11\x62lendShapeWeights\x18\x04 \x03(\x02\x12\x10\n\x08headPosX\x18\x05 \x01(\x02\x12\x10\n\x08headPosY\x18\x06 \x01(\x02\x12\x10\n\x08headPosZ\x18\x07 \x01(\x02\x12\x10\n\x08headRotX\x18\x08 \x01(\x02\x12\x10\n\x08headRotY\x18\t \x01(\x02\x12\x10\n\x08headRotZ\x18\n \x01(\x02\x12\x10\n\x08headRotW\x18\x0b \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FaceSample_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FACESAMPLE']._serialized_start=21
  _globals['_FACESAMPLE']._serialized_end=242
# @@protoc_insertion_point(module_scope)
